//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemADM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class systemADMEntities1 : DbContext
    {
        public systemADMEntities1()
            : base("name=systemADMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> budynki { get; set; }
        public virtual DbSet<Note> notatki { get; set; }
        public virtual DbSet<Role> role { get; set; }
        public virtual DbSet<Status> statusy { get; set; }
        public virtual DbSet<User> users { get; set; }
        public virtual DbSet<Ticket> zgloszenia { get; set; }
    }
}
