//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemADM.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Note
    {

        public Note()
        {
            this.data_wpisania = DateTime.Now;
        }
        [Display(Name = "Notatka")]
        public int id_notatki { get; set; }
        [Display(Name = "Autor notatki")] 
        public int id_uzytkownik { get; set; }
        [Display(Name = "ID zg³oszenia")] 
        public int id_zgloszenia { get; set; }
        [Display(Name = "Treœæ")] 
        public string tresc { get; set; }
        [Display(Name = "Data dodania")] 
        public Nullable<System.DateTime> data_wpisania { get; private set; }

        public virtual User users { get; set; }
        public virtual Ticket zgloszenia { get; set; }
    }
}
