//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemADM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.notatki = new HashSet<Note>();
            this.data_zgloszenia = DateTime.Now;
        }

        [Display(Name = "ID zg³oszenia")]
        public int id_zgloszenia { get; set; }

        [Display(Name = "Status")]
        public int id_status { get; set; }

        [Display(Name = "Zg³aszaj¹cy")] 
        public int id_uzytkownik { get; set; }

        [Display(Name = "Budynek")] 
        public int id_budynek { get; set; }

        [Display(Name = "Temat")] 
        public string temat { get; set; }

        [Display(Name = "Opis")] 
        public string opis { get; set; }

        [Display(Name = "Data zg³oszenia")] 
        public Nullable<System.DateTime> data_zgloszenia { get; private set; }

        [Display(Name = "Data wykonania")] 
        public Nullable<System.DateTime> data_wykonania { get; set; }

        [Display(Name = "Planowana data wykonania")] 
        public Nullable<System.DateTime> planowana_data_wykonania { get; set; }



        public virtual Building budynki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> notatki { get; set; }
        public virtual Status statusy { get; set; }
        public virtual User users { get; set; }
    }
}
