//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemADM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.data_rejestracji = DateTime.Now;
            this.notatki = new HashSet<Note>();
            this.zgloszenia = new HashSet<Ticket>();
            this.budynki = new HashSet<Building>();
        }
        [Display(Name = "U¿ytkownik")]
        public string FullName
        {
            get
            {
                return imie + " " + nazwisko;
            }
        }

        [Display(Name = "U¿ytkownik")]
        public int id_uzytkownik { get; set; }
        [Display(Name = "Uprawnienia")] public int id_rola { get; set; }
        [Display(Name = "Imiê")] public string imie { get; set; }
        [Display(Name = "Nazwisko")] public string nazwisko { get; set; }
        [Display(Name = "E-mail")] public string email { get; set; }
        [Display(Name = "Telefon")] public string telefon { get; set; }
        [Display(Name = "Data rejestracji")] public System.DateTime data_rejestracji { get; private set; }
        
        [DataType(DataType.Password)]
        [Display(Name = "Has³o")] public string haslo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> notatki { get; set; }
        public virtual Role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> zgloszenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Building> budynki { get; set; }
 
    }
}
